CREATE TABLE `post`(
    `post_id` INT(11) NOT NULL AUTO_INCREMENT,
    `message` VARCHAR(500) NOT NULL,
    `created_at` DATETIME DEFAULT  CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`post_id`),
    FOREIGN KEY(`user_id`) REFERENCES user(`user_id`)
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;